# Plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Terminale e colori
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Indici a partire da 1
set -g base-index 1
setw -g pane-base-index 1

# Mouse
set -g mouse on

# Nuove finestre/pannelli ereditano la cwd del pannello attivo
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind %  split-window -h -c "#{pane_current_path}"

# Modalità copia in stile vi
setw -g mode-keys vi
bind v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

# Sessionizer
bind-key f run-shell "tmux neww tmux-sessionizer"

# Ricarica della configurazione
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf sourced"

# Aspetto
set -g status-style 'bg=#333333 fg=#84a8b9'

# Avvio plugin (deve restare l'ultima riga)
run '~/.tmux/plugins/tpm/tpm'
